# Build stage I: 
FROM mcr.microsoft.com/oss/go/microsoft/golang:1.23.2-1-bullseye AS build

WORKDIR /basicservice
COPY . .


ARG PAT
RUN echo "export GOPRIVATE='dev.azure.com'" >> ~/.bashrc
RUN git config --global url."https://$PAT@dev.azure.com/service-hub-flg/service_hub_validation/_git/service_hub_validation_service".insteadOf "https://dev.azure.com/service-hub-flg/service_hub_validation/_git/service_hub_validation_service"


RUN cd api && go mod tidy && go build ./...
RUN cd server && go mod tidy && go get google.golang.org/genproto@latest

# The output will be in the current directory.
# The path is the complete package path. No main name in the path.
RUN cd server && go build dev.azure.com/service-hub-flg/service_hub_validation/_git/service_hub_validation_service.git/basicservice/server/cmd/client
RUN cd server && go build dev.azure.com/service-hub-flg/service_hub_validation/_git/service_hub_validation_service.git/basicservice/server/cmd/demoserver
RUN cd server && go build dev.azure.com/service-hub-flg/service_hub_validation/_git/service_hub_validation_service.git/basicservice/server/cmd/server


# Build stage II: 
# FROM scratch
# FROM busybox
FROM mcr.microsoft.com/openjdk/jdk:17-ubuntu
COPY --from=build /basicservice/server/client /
COPY --from=build basicservice//server/demoserver /
COPY --from=build /basicservice/server/server /

CMD ["/server"]
